'use client';
import {Canvas,ThreeEvent,useThree} from '@react-three/fiber';
import {OrbitControls,Html} from '@react-three/drei';
import {useEffect,useMemo,useRef,useState} from 'react';import * as THREE from 'three';
import {tools,targets,State,Action} from '@/lib/lab';
function Glass({children}:{children:React.ReactNode}){return <group>{children}</group>}
export function Model({id,pink=false,filled=false,over=false}:{id:string;pink?:boolean;filled?:boolean;over?:boolean}){
 const lathe=useMemo(()=>new THREE.LatheGeometry([new THREE.Vector2(.03,0),new THREE.Vector2(.24,.02),new THREE.Vector2(.26,.1),new THREE.Vector2(.09,.43),new THREE.Vector2(.085,.61),new THREE.Vector2(.1,.63)],16),[]);
 const glass=<meshStandardMaterial color="#d1e2df" transparent opacity={.42} roughness={.3} side={THREE.DoubleSide}/>;
 const kind=tools.find(t=>t.id===id)?.kind;
 if(kind==='flask')return <Glass><mesh geometry={lathe}>{glass}</mesh>{filled&&<mesh position={[0,.12,0]}><cylinderGeometry args={[.18,.23,.2,16]}/><meshStandardMaterial color={over?'#c9368a':pink?'#f5bfd6':'#e6ebe5'} transparent opacity={.85}/></mesh>}<mesh position={[0,.35,.095]}><boxGeometry args={[.08,.025,.015]}/><meshStandardMaterial color="white"/></mesh></Glass>;
 if(kind==='stand')return <group><mesh position={[0,.025,0]}><boxGeometry args={[.65,.07,.5]}/><meshStandardMaterial color="#404843"/></mesh><mesh position={[0,1,0]}><cylinderGeometry args={[.025,.025,2,8]}/><meshStandardMaterial color="#9caba5" metalness={.5}/></mesh><mesh position={[.19,1.55,0]}><boxGeometry args={[.4,.065,.06]}/><meshStandardMaterial color="#545b55"/></mesh></group>;
 if(kind==='burette')return <group><mesh position={[0,.92,0]}><cylinderGeometry args={[.05,.05,1.7,12]}/>{glass}</mesh><mesh position={[0,.85,0]}><cylinderGeometry args={[.035,.035,1.3,12]}/><meshStandardMaterial color="#a3c5c3" transparent opacity={.55}/></mesh>{Array.from({length:18},(_,i)=><mesh key={i} position={[0,.2+i*.08,.052]}><boxGeometry args={[i%5===0?.08:.045,.006,.004]}/><meshBasicMaterial color="#3a4842"/></mesh>)}<mesh position={[0,.08,0]}><cylinderGeometry args={[.018,.01,.2,8]}/>{glass}</mesh><mesh position={[.07,.19,0]}><boxGeometry args={[.2,.04,.045]}/><meshStandardMaterial color="#bc3636"/></mesh></group>;
 if(kind==='pipette')return <group rotation={[0,0,Math.PI/2]}><mesh position={[0,.35,0]}><cylinderGeometry args={[.018,.012,.7,8]}/>{glass}</mesh><mesh position={[0,.37,0]}><sphereGeometry args={[.07,12,8]}/>{glass}</mesh><mesh position={[0,.75,0]}><sphereGeometry args={[.09,12,8]}/><meshStandardMaterial color="#b93737"/></mesh></group>;
 if(kind==='funnel')return <group><mesh position={[0,.19,0]}><coneGeometry args={[.19,.2,12,1,true]}/>{glass}</mesh><mesh position={[0,.05,0]}><cylinderGeometry args={[.025,.025,.2,8]}/>{glass}</mesh></group>;
 if(id==='goggles')return <group position={[0,.16,0]}><mesh position={[-.14,0,0]} scale={[1.35,.82,1]}><torusGeometry args={[.105,.018,10,24]}/><meshStandardMaterial color="#293a3a"/></mesh><mesh position={[.14,0,0]} scale={[1.35,.82,1]}><torusGeometry args={[.105,.018,10,24]}/><meshStandardMaterial color="#293a3a"/></mesh><mesh position={[-.14,0,-.006]} scale={[1.2,.72,1]}><circleGeometry args={[.095,24]}/><meshStandardMaterial color="#b9d5d2" transparent opacity={.45}/></mesh><mesh position={[.14,0,-.006]} scale={[1.2,.72,1]}><circleGeometry args={[.095,24]}/><meshStandardMaterial color="#b9d5d2" transparent opacity={.45}/></mesh><mesh position={[0,0,0]}><boxGeometry args={[.075,.025,.025]}/><meshStandardMaterial color="#293a3a"/></mesh><mesh position={[0,0,-.04]} scale={[1.1,.65,1]}><torusGeometry args={[.29,.012,8,24,Math.PI]}/><meshStandardMaterial color="#536664"/></mesh></group>;
 if(id==='coat')return <group position={[0,.35,0]}><mesh position={[0,0,0]}><boxGeometry args={[.38,.62,.1]}/><meshStandardMaterial color="#f4f3ef"/></mesh><mesh position={[-.28,.02,0]} rotation={[0,0,-.18]}><capsuleGeometry args={[.065,.45,6,12]}/><meshStandardMaterial color="#efeee9"/></mesh><mesh position={[.28,.02,0]} rotation={[0,0,.18]}><capsuleGeometry args={[.065,.45,6,12]}/><meshStandardMaterial color="#efeee9"/></mesh><mesh position={[-.09,.18,.06]} rotation={[0,0,-.35]}><boxGeometry args={[.16,.28,.018]}/><meshStandardMaterial color="#deddd8"/></mesh><mesh position={[.09,.18,.06]} rotation={[0,0,.35]}><boxGeometry args={[.16,.28,.018]}/><meshStandardMaterial color="#e8e7e2"/></mesh><mesh position={[0,-.05,.06]}><boxGeometry args={[.015,.46,.018]}/><meshStandardMaterial color="#aeb2ad"/></mesh>{[-.12,.12].map(x=><mesh key={x} position={[x,-.15,.065]}><boxGeometry args={[.12,.1,.02]}/><meshStandardMaterial color="#d8d8d3"/></mesh>)}</group>;
 if(id==='gloves')return <group position={[0,.12,0]} rotation={[-.18,0,-.25]}><mesh scale={[1.1,.8,.55]}><sphereGeometry args={[.15,18,12]}/><meshStandardMaterial color="#78a7bb"/></mesh>{[-.1,-.035,.035,.1].map((x,i)=><mesh key={x} position={[x,.17+(i%2)*.015,0]}><capsuleGeometry args={[.026,.17,5,8]}/><meshStandardMaterial color="#78a7bb"/></mesh>)}<mesh position={[-.16,.06,0]} rotation={[0,0,-.7]}><capsuleGeometry args={[.03,.14,5,8]}/><meshStandardMaterial color="#78a7bb"/></mesh><mesh position={[0,-.16,0]}><cylinderGeometry args={[.105,.13,.18,14]}/><meshStandardMaterial color="#6999ae"/></mesh></group>;
 if(kind==='beaker')return <mesh position={[0,.2,0]}><cylinderGeometry args={[.19,.18,.4,12,1,true]}/>{glass}</mesh>;
 return <group><mesh position={[0,.23,0]}><cylinderGeometry args={[.15,.17,.46,12]}/><meshStandardMaterial color={id==='indicator'?'#765340':'#e2e4dc'}/></mesh><mesh position={[0,.5,0]}><cylinderGeometry args={[.09,.09,.12,12]}/><meshStandardMaterial color={id==='naoh'?'#bc3636':'#333d37'}/></mesh><mesh position={[0,.26,.153]}><boxGeometry args={[.2,.19,.008]}/><meshStandardMaterial color="#fffdf6"/></mesh><mesh position={[0,.23,.16]}><boxGeometry args={[.14,.02,.01]}/><meshStandardMaterial color={id==='naoh'?'#bc3636':'#353d38'}/></mesh></group>
}
function Item({obj,state,dispatch,select,selected,cameraMode}:{obj:State['objects'][number];state:State;dispatch:React.Dispatch<Action>;select:(id:string)=>void;selected:boolean;cameraMode:boolean}){
 const [hover,setHover]=useState(false);const dragging=useRef(false);const {raycaster,invalidate}=useThree();const plane=useMemo(()=>new THREE.Plane(new THREE.Vector3(0,1,0),-.87),[]);
 function move(e:ThreeEvent<PointerEvent>){if(cameraMode||!dragging.current||obj.locked)return;e.stopPropagation();const p=new THREE.Vector3();if(raycaster.ray.intersectPlane(plane,p)){dispatch({type:'move',id:obj.id,pos:[Math.max(-2.5,Math.min(2.5,p.x)),.87,Math.max(-1,Math.min(1,p.z))]});invalidate()}}
 function up(e:ThreeEvent<PointerEvent>){e.stopPropagation();dragging.current=false;(e.target as Element).releasePointerCapture?.(e.pointerId);const t=targets[obj.id];if(t&&Math.hypot(obj.pos[0]-t[0],obj.pos[2]-t[2])<.5&&!obj.locked)dispatch({type:'lock',id:obj.id})}
 return <group position={obj.pos} onPointerOver={e=>{e.stopPropagation();setHover(true)}} onPointerOut={()=>setHover(false)} onPointerDown={e=>{if(cameraMode)return;e.stopPropagation();select(obj.id);dragging.current=!obj.locked;(e.target as Element).setPointerCapture?.(e.pointerId)}} onPointerMove={move} onPointerUp={up}>
 <Model id={obj.id} filled={state.step>=6} pink={state.indicator&&state.volume>=24.8} over={state.volume>25.05}/>{(hover||selected)&&<Html position={[0,tools.find(t=>t.id===obj.id)?.kind==='burette'?2:.8,0]} center style={{pointerEvents:'none',whiteSpace:'nowrap'}}><span className="object-label">{tools.find(t=>t.id===obj.id)?.name}{obj.locked?' · terkunci':''}</span></Html>}
 {selected&&<mesh rotation={[-Math.PI/2,0,0]} position={[0,.006,0]}><ringGeometry args={[.3,.32,24]}/><meshBasicMaterial color="#c62828" side={THREE.DoubleSide}/></mesh>}</group>
}
function Room(){return <group><mesh position={[0,-.1,0]}><boxGeometry args={[8,.15,6]}/><meshStandardMaterial color="#eeeee7"/></mesh><mesh position={[0,1.4,-2.6]}><boxGeometry args={[8,3,.1]}/><meshStandardMaterial color="#e0e3da"/></mesh><mesh position={[-3.8,1.4,0]}><boxGeometry args={[.1,3,5.2]}/><meshStandardMaterial color="#d6dcd3"/></mesh><mesh position={[0,.75,0]}><boxGeometry args={[5.8,.2,2.8]}/><meshStandardMaterial color="#e0d1b3"/></mesh><mesh position={[0,.64,0]}><boxGeometry args={[5.8,.06,2.8]}/><meshStandardMaterial color="#6b736a"/></mesh>{[-2.5,2.5].flatMap(x=>[-1,1].map(z=><mesh key={`${x}${z}`} position={[x,.3,z]}><boxGeometry args={[.1,.7,.1]}/><meshStandardMaterial color="#59665c"/></mesh>))}<mesh position={[1.8,1.6,-2.48]}><boxGeometry args={[2.1,1,.06]}/><meshStandardMaterial color="#f7f9ee"/></mesh><mesh position={[-2,1.2,-2.4]}><boxGeometry args={[1.5,.08,.45]}/><meshStandardMaterial color="#8c978b"/></mesh>{[-2.4,-2,-1.6].map((x,i)=><group key={x} position={[x,1.24,-2.35]} scale={.7}><Model id={i?'water':'naoh'}/></group>)}<mesh position={[-2.5,.88,.9]}><boxGeometry args={[.55,.04,.35]}/><meshStandardMaterial color="#f6f4e8"/></mesh></group>}
function CameraReset({resetKey}:{resetKey:number}){const {camera,invalidate}=useThree();useEffect(()=>{camera.position.set(7,6,8);camera.lookAt(0,.7,0);if('zoom' in camera){camera.zoom=75;camera.updateProjectionMatrix()}invalidate()},[camera,invalidate,resetKey]);return null}
export default function Scene({state,dispatch,selected,select,cameraMode,resetKey}:{state:State;dispatch:React.Dispatch<Action>;selected:string|null;select:(id:string)=>void;cameraMode:boolean;resetKey:number}){return <Canvas orthographic camera={{position:[7,6,8],zoom:75}} dpr={[1,1.5]} frameloop="demand" fallback={<p>WebGL2 tidak tersedia. Gunakan browser terbaru untuk membuka lab.</p>}><CameraReset resetKey={resetKey}/><color attach="background" args={['#f2f3ed']}/><ambientLight intensity={1.6}/><directionalLight position={[5,9,5]} intensity={2}/><Room/>{state.mode==='latihan'&&Object.entries(targets).map(([id,p])=><mesh key={id} position={[p[0],.866,p[2]]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[.28,.3,32]}/><meshBasicMaterial color="#bc5757" transparent opacity={.6}/></mesh>)}{state.objects.map(obj=><Item key={obj.id} obj={obj} state={state} dispatch={dispatch} selected={selected===obj.id} select={select} cameraMode={cameraMode}/>)}<OrbitControls makeDefault enableRotate={false} enablePan={cameraMode} enableZoom minZoom={55} maxZoom={125} target={[0,.7,0]} mouseButtons={{LEFT:THREE.MOUSE.PAN,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.PAN}} touches={{ONE:THREE.TOUCH.PAN,TWO:THREE.TOUCH.DOLLY_PAN}}/></Canvas>}
export function Preview({id}:{id:string}){return <Canvas camera={{position:[2,1.6,3],fov:35}} dpr={1}><ambientLight intensity={2}/><directionalLight position={[3,4,3]} intensity={2}/><group position={[0,-.4,0]} scale={tools.find(t=>t.id===id)?.kind==='burette'?.7:1.4}><Model id={id}/></group><OrbitControls autoRotate enableZoom={false} enablePan={false}/></Canvas>}
