'use client';
import {Canvas,ThreeEvent,useFrame,useThree} from '@react-three/fiber';
import {OrbitControls,Html} from '@react-three/drei';
import {useEffect,useMemo,useRef,useState} from 'react';import * as THREE from 'three';
import {tools,targets,State,Action} from '@/lib/lab';
function Glass({children}:{children:React.ReactNode}){return <group>{children}</group>}
export function Model({id,pink=false,filled=false,over=false,loaded=false}:{id:string;pink?:boolean;filled?:boolean;over?:boolean;loaded?:boolean}){
 const lathe=useMemo(()=>new THREE.LatheGeometry([new THREE.Vector2(.03,0),new THREE.Vector2(.24,.02),new THREE.Vector2(.26,.1),new THREE.Vector2(.09,.43),new THREE.Vector2(.085,.61),new THREE.Vector2(.1,.63)],16),[]);
 const bottleLabel=useMemo(()=>{if(typeof document==='undefined')return null;const canvas=document.createElement('canvas');canvas.width=256;canvas.height=144;const context=canvas.getContext('2d');if(!context)return null;context.fillStyle='#fffdf7';context.fillRect(0,0,256,144);context.strokeStyle='#c8323b';context.lineWidth=7;context.strokeRect(9,9,52,52);context.fillStyle='#202522';context.font='700 44px sans-serif';context.fillText(({naoh:'NaOH',hcl:'HCl',indicator:'PhPh',water:'H₂O'} as Record<string,string>)[id]||id,74,57);context.font='22px sans-serif';context.fillStyle='#59615c';context.fillText(id==='indicator'?'Indikator':id==='water'?'Deionisasi':'Larutan',74,94);context.fillStyle='#c8323b';context.beginPath();context.arc(35,35,8,0,Math.PI*2);context.fill();const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture},[id]);
 const glass=<meshPhysicalMaterial color="#f4ffff" emissive="#d9f2ef" emissiveIntensity={.14} transparent opacity={.67} roughness={.08} metalness={0} transmission={.06} side={THREE.DoubleSide}/>;
 const kind=tools.find(t=>t.id===id)?.kind;
 if(kind==='flask')return <Glass><mesh geometry={lathe}>{glass}</mesh>{filled&&<mesh position={[0,.12,0]}><cylinderGeometry args={[.18,.23,.2,16]}/><meshStandardMaterial color={over?'#c9368a':pink?'#f5bfd6':'#e6ebe5'} transparent opacity={.85}/></mesh>}<mesh position={[0,.35,.095]}><boxGeometry args={[.08,.025,.015]}/><meshStandardMaterial color="white"/></mesh></Glass>;
 if(kind==='stand')return <group><mesh position={[0,.025,0]}><boxGeometry args={[.65,.07,.5]}/><meshStandardMaterial color="#404843"/></mesh><mesh position={[0,1,0]}><cylinderGeometry args={[.025,.025,2,8]}/><meshStandardMaterial color="#9caba5" metalness={.5}/></mesh><mesh position={[.19,1.55,0]}><boxGeometry args={[.4,.065,.06]}/><meshStandardMaterial color="#545b55"/></mesh></group>;
 if(kind==='burette')return <group><mesh position={[0,.72,0]}><cylinderGeometry args={[.042,.042,1.3,12]}/>{glass}</mesh><mesh position={[0,.67,0]}><cylinderGeometry args={[.028,.028,.96,12]}/><meshStandardMaterial color="#a3c5c3" transparent opacity={.58}/></mesh>{Array.from({length:15},(_,i)=><mesh key={i} position={[0,.18+i*.075,.044]}><boxGeometry args={[i%5===0?.068:.038,.005,.004]}/><meshBasicMaterial color="#3a4842"/></mesh>)}<mesh position={[0,.07,0]}><cylinderGeometry args={[.015,.008,.17,8]}/>{glass}</mesh><mesh position={[.055,.17,0]}><boxGeometry args={[.16,.035,.04]}/><meshStandardMaterial color="#bc3636"/></mesh></group>;
 if(kind==='pipette')return <group rotation={[0,0,Math.PI/2]}><mesh position={[0,.45,0]}><cylinderGeometry args={[.012,.008,.88,10]}/>{glass}</mesh>{loaded&&<mesh position={[0,.38,0]}><cylinderGeometry args={[.008,.006,.56,8]}/><meshStandardMaterial color="#9fc8c3" transparent opacity={.82}/></mesh>}<mesh position={[0,.48,0]} scale={[1,2.5,1]}><sphereGeometry args={[.038,14,10]}/>{glass}</mesh><mesh position={[0,.96,0]} scale={[.8,1.25,.8]}><sphereGeometry args={[.075,14,10]}/><meshStandardMaterial color="#b93737" roughness={.45}/></mesh></group>;
 if(kind==='funnel')return <group><mesh position={[0,.2,0]}><coneGeometry args={[.14,.17,20,1,true]}/>{glass}</mesh><mesh position={[0,.065,0]}><cylinderGeometry args={[.018,.013,.2,12]}/>{glass}</mesh><mesh position={[0,.288,0]}><torusGeometry args={[.14,.012,8,24]}/><meshStandardMaterial color="#d7eeeb" emissive="#dff7f4" emissiveIntensity={.18}/></mesh></group>;
 if(id==='goggles')return <group position={[0,.16,0]}><mesh position={[-.14,0,0]} scale={[1.35,.82,1]}><torusGeometry args={[.105,.018,10,24]}/><meshStandardMaterial color="#293a3a"/></mesh><mesh position={[.14,0,0]} scale={[1.35,.82,1]}><torusGeometry args={[.105,.018,10,24]}/><meshStandardMaterial color="#293a3a"/></mesh><mesh position={[-.14,0,-.006]} scale={[1.2,.72,1]}><circleGeometry args={[.095,24]}/><meshStandardMaterial color="#b9d5d2" transparent opacity={.45}/></mesh><mesh position={[.14,0,-.006]} scale={[1.2,.72,1]}><circleGeometry args={[.095,24]}/><meshStandardMaterial color="#b9d5d2" transparent opacity={.45}/></mesh><mesh position={[0,0,0]}><boxGeometry args={[.075,.025,.025]}/><meshStandardMaterial color="#293a3a"/></mesh><mesh position={[0,0,-.04]} scale={[1.1,.65,1]}><torusGeometry args={[.29,.012,8,24,Math.PI]}/><meshStandardMaterial color="#536664"/></mesh></group>;
 if(id==='coat')return <group position={[0,.35,0]}><mesh position={[0,0,0]}><boxGeometry args={[.38,.62,.1]}/><meshStandardMaterial color="#f4f3ef"/></mesh><mesh position={[-.28,.02,0]} rotation={[0,0,-.18]}><capsuleGeometry args={[.065,.45,6,12]}/><meshStandardMaterial color="#efeee9"/></mesh><mesh position={[.28,.02,0]} rotation={[0,0,.18]}><capsuleGeometry args={[.065,.45,6,12]}/><meshStandardMaterial color="#efeee9"/></mesh><mesh position={[-.09,.18,.06]} rotation={[0,0,-.35]}><boxGeometry args={[.16,.28,.018]}/><meshStandardMaterial color="#deddd8"/></mesh><mesh position={[.09,.18,.06]} rotation={[0,0,.35]}><boxGeometry args={[.16,.28,.018]}/><meshStandardMaterial color="#e8e7e2"/></mesh><mesh position={[0,-.05,.06]}><boxGeometry args={[.015,.46,.018]}/><meshStandardMaterial color="#aeb2ad"/></mesh>{[-.12,.12].map(x=><mesh key={x} position={[x,-.15,.065]}><boxGeometry args={[.12,.1,.02]}/><meshStandardMaterial color="#d8d8d3"/></mesh>)}</group>;
 if(id==='gloves')return <group position={[0,.12,0]} rotation={[-.18,0,-.25]}><mesh scale={[1.1,.8,.55]}><sphereGeometry args={[.15,18,12]}/><meshStandardMaterial color="#78a7bb"/></mesh>{[-.1,-.035,.035,.1].map((x,i)=><mesh key={x} position={[x,.17+(i%2)*.015,0]}><capsuleGeometry args={[.026,.17,5,8]}/><meshStandardMaterial color="#78a7bb"/></mesh>)}<mesh position={[-.16,.06,0]} rotation={[0,0,-.7]}><capsuleGeometry args={[.03,.14,5,8]}/><meshStandardMaterial color="#78a7bb"/></mesh><mesh position={[0,-.16,0]}><cylinderGeometry args={[.105,.13,.18,14]}/><meshStandardMaterial color="#6999ae"/></mesh></group>;
 if(kind==='beaker')return <group><mesh position={[0,.16,0]}><cylinderGeometry args={[.15,.14,.32,20,1,true]}/>{glass}</mesh><mesh position={[0,.32,0]}><torusGeometry args={[.15,.012,8,24]}/><meshStandardMaterial color="#d7eeeb" emissive="#e8ffff" emissiveIntensity={.15}/></mesh></group>;
 return <group><mesh position={[0,.22,0]}><cylinderGeometry args={[.16,.18,.42,20]}/><meshStandardMaterial color={id==='indicator'?'#8b684e':'#e8e9e3'} roughness={.35}/></mesh><mesh position={[0,.43,0]}><sphereGeometry args={[.15,20,12,0,Math.PI*2,0,Math.PI/2]}/><meshStandardMaterial color={id==='indicator'?'#8b684e':'#e8e9e3'} roughness={.35}/></mesh><mesh position={[0,.53,0]}><cylinderGeometry args={[.085,.085,.14,20]}/><meshStandardMaterial color={id==='naoh'?'#b72d37':id==='water'?'#315d70':'#27312c'} roughness={.55}/></mesh><mesh position={[0,.25,.171]}><planeGeometry args={[.27,.15]}/><meshBasicMaterial map={bottleLabel||undefined} toneMapped={false}/></mesh><mesh position={[0,.08,0]}><cylinderGeometry args={[.145,.16,.11,20]}/><meshStandardMaterial color={id==='indicator'?'#704632':id==='naoh'?'#d9e6e2':id==='hcl'?'#e7dfd0':'#cfe3e9'} transparent opacity={.72}/></mesh></group>
}
function Item({obj,state,dispatch,select,selected,cameraMode,onInteract,modalOpen}:{obj:State['objects'][number];state:State;dispatch:React.Dispatch<Action>;select:(id:string)=>void;selected:boolean;cameraMode:boolean;onInteract:()=>void;modalOpen?:boolean}){
 const [hover,setHover]=useState(false);const dragging=useRef(false);const lastPos=useRef<[number,number,number]|null>(null);const {raycaster,invalidate}=useThree();const plane=useMemo(()=>new THREE.Plane(new THREE.Vector3(0,1,0),-.87),[]);
 const kind=tools.find(tool=>tool.id===obj.id)?.kind;const modelScale=kind==='stand'?1:kind==='burette'?.92:kind==='pipette'?.9:kind==='flask'?.82:kind==='funnel'?.9:kind==='beaker'?.86:kind==='bottle'?.92:1;
 const near=(id:string,p:[number,number,number],distance=.62)=>{const other=state.objects.find(item=>item.id===id);return !!other&&Math.hypot(p[0]-other.pos[0],p[2]-other.pos[2])<distance};
 function move(e:ThreeEvent<PointerEvent>){if(cameraMode||!dragging.current||obj.locked)return;e.stopPropagation();const point=new THREE.Vector3();if(raycaster.ray.intersectPlane(plane,point)){let x=Math.max(-2.5,Math.min(2.5,point.x)),z=Math.max(-1,Math.min(1,point.z));if(state.step===8&&obj.id==='flask'){x=Math.max(-.68,Math.min(.08,x));z=Math.max(-.18,Math.min(.52,z));dispatch({type:'mix'})}const pos:[number,number,number]=[x,.87,z];lastPos.current=pos;dispatch({type:'move',id:obj.id,pos});invalidate()}}
 function up(e:ThreeEvent<PointerEvent>){e.stopPropagation();dragging.current=false;(e.target as Element).releasePointerCapture?.(e.pointerId);const p=lastPos.current||obj.pos;lastPos.current=null;
  if(state.step===1&&['stand','burette'].includes(obj.id)){const t=targets[obj.id];if(Math.hypot(p[0]-t[0],p[2]-t[2])<.58){dispatch({type:'move',id:obj.id,pos:t});dispatch({type:'lock',id:obj.id});return}}
  if(state.step===2&&obj.id==='naoh'&&near('burette',p)){dispatch({type:'rinse'});return}
  if(state.step===3&&obj.id==='funnel'&&near('burette',p)){dispatch({type:'placeFunnel'});return}
  if(state.step===3&&obj.id==='naoh'&&state.funnelPlaced&&near('burette',p)){dispatch({type:'fill'});return}
  if(state.step===4&&obj.id==='funnel'&&!near('burette',p,.85)){dispatch({type:'record'});return}
  if(state.step===5&&obj.id==='pipette'&&near('hcl',p)){dispatch({type:'loadPipette'});return}
  if(state.step===5&&obj.id==='pipette'&&state.pipetteLoaded&&near('flask',p)){dispatch({type:'pipette'});return}
  if(state.step===6&&obj.id==='indicator'&&near('flask',p)){dispatch({type:'indicator'});return}
  if(state.step===7&&obj.id==='flask'){const t=targets.flask;if(Math.hypot(p[0]-t[0],p[2]-t[2])<.6){dispatch({type:'move',id:'flask',pos:t});dispatch({type:'ready'});return}}
  if(state.step===8&&obj.id==='flask'){dispatch({type:'move',id:'flask',pos:targets.flask});dispatch({type:'mix'})}
 }
 return <group position={obj.pos} onPointerOver={e=>{e.stopPropagation();setHover(true)}} onPointerOut={()=>setHover(false)} onPointerDown={e=>{if(cameraMode)return;e.stopPropagation();onInteract();select(obj.id);dragging.current=!obj.locked;(e.target as Element).setPointerCapture?.(e.pointerId)}} onPointerMove={move} onPointerUp={up}>
 <group scale={modelScale}><Model id={obj.id} filled={state.step>=6} pink={state.indicator&&state.volume>=24.8} loaded={obj.id==='pipette'&&state.pipetteLoaded}/></group>{!modalOpen&&(hover||selected)&&<Html position={[0,kind==='burette'?1.55:1,0]} center style={{pointerEvents:'none',whiteSpace:'nowrap'}}><span className="object-label">{tools.find(t=>t.id===obj.id)?.name}{obj.locked?' · terpasang':''}</span></Html>}
 {selected&&<mesh rotation={[-Math.PI/2,0,0]} position={[0,.006,0]}><ringGeometry args={[.3,.32,24]}/><meshBasicMaterial color="#c62828" side={THREE.DoubleSide}/></mesh>}</group>
}
function Room(){return <group><mesh position={[0,-.1,0]}><boxGeometry args={[8,.15,6]}/><meshStandardMaterial color="#eeeee7"/></mesh><mesh position={[0,1.4,-2.6]}><boxGeometry args={[8,3,.1]}/><meshStandardMaterial color="#e0e3da"/></mesh><mesh position={[-3.8,1.4,0]}><boxGeometry args={[.1,3,5.2]}/><meshStandardMaterial color="#d6dcd3"/></mesh><mesh position={[0,.75,0]}><boxGeometry args={[6.8,.2,3.6]}/><meshStandardMaterial color="#e0d1b3"/></mesh><mesh position={[0,.64,0]}><boxGeometry args={[6.8,.06,3.6]}/><meshStandardMaterial color="#6b736a"/></mesh>{[-3,3].flatMap(x=>[-1.4,1.4].map(z=><mesh key={`${x}${z}`} position={[x,.3,z]}><boxGeometry args={[.1,.7,.1]}/><meshStandardMaterial color="#59665c"/></mesh>))}<mesh position={[1.8,1.6,-2.48]}><boxGeometry args={[2.1,1,.06]}/><meshStandardMaterial color="#f7f9ee"/></mesh><mesh position={[-2.9,.88,1.25]}><boxGeometry args={[.55,.04,.35]}/><meshStandardMaterial color="#f6f4e8"/></mesh></group>}
function Particles(){const ref=useRef<THREE.Points>(null);const positions=useMemo(()=>{const values=new Float32Array(90);for(let i=0;i<30;i++){values[i*3]=(Math.random()-.5)*6;values[i*3+1]=.9+Math.random()*2;values[i*3+2]=-1.8+Math.random()*3.6}return values},[]);useFrame((_,delta)=>{if(ref.current)ref.current.rotation.y+=delta*.018});return <points ref={ref}><bufferGeometry><bufferAttribute attach="attributes-position" args={[positions,3]}/></bufferGeometry><pointsMaterial color="#9fb4aa" size={.035} transparent opacity={.48} sizeAttenuation/></points>}
function CameraReset({resetKey}:{resetKey:number}){const {camera,invalidate}=useThree();useEffect(()=>{camera.position.set(7,6,8);camera.lookAt(0,.7,0);if('zoom' in camera){camera.zoom=75;camera.updateProjectionMatrix()}invalidate()},[camera,invalidate,resetKey]);return null}
export default function Scene({state,dispatch,selected,select,cameraMode,resetKey,onInteract,modalOpen}:{state:State;dispatch:React.Dispatch<Action>;selected:string|null;select:(id:string)=>void;cameraMode:boolean;resetKey:number;onInteract:()=>void;modalOpen?:boolean}){const snapIds=state.step===1?['stand','burette']:state.step===7?['flask']:[];return <Canvas orthographic camera={{position:[7,6,8],zoom:75}} dpr={[1,1.5]} frameloop="always" fallback={<p>WebGL2 tidak tersedia. Gunakan browser terbaru untuk membuka lab.</p>}><CameraReset resetKey={resetKey}/><color attach="background" args={['#f2f3ed']}/><hemisphereLight color="#ffffff" groundColor="#c8d1c8" intensity={1.8}/><directionalLight position={[5,9,5]} intensity={2.2}/><pointLight position={[-2,4,2]} intensity={1.2} color="#e8ffff"/><Particles/><Room/>{state.mode==='latihan'&&snapIds.map(id=>{const p=targets[id];return <mesh key={id} position={[p[0],.866,p[2]]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[.28,.3,32]}/><meshBasicMaterial color="#bc5757" transparent opacity={.6}/></mesh>})}{state.objects.map(obj=><Item key={obj.id} obj={obj} state={state} dispatch={dispatch} selected={selected===obj.id} select={select} cameraMode={cameraMode} onInteract={onInteract} modalOpen={modalOpen}/>)}<OrbitControls makeDefault enableRotate={false} enablePan={cameraMode} enableZoom minZoom={55} maxZoom={125} target={[0,.7,0]} mouseButtons={{LEFT:THREE.MOUSE.PAN,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.PAN}} touches={{ONE:THREE.TOUCH.PAN,TWO:THREE.TOUCH.DOLLY_PAN}}/></Canvas>}
export function Preview({id}:{id:string}){return <Canvas camera={{position:[2,1.6,3],fov:35}} dpr={1}><ambientLight intensity={2}/><directionalLight position={[3,4,3]} intensity={2}/><group position={[0,-.4,0]} scale={tools.find(t=>t.id===id)?.kind==='burette'?.7:1.4}><Model id={id}/></group><OrbitControls autoRotate enableZoom={false} enablePan={false}/></Canvas>}
