import {describe,it,expect} from 'vitest';
import {initial,reducer,ready,score,structureAt,epidermisTools,type State} from './epidermis';
import {tools} from './lab';
import {getPreviewAsset} from './previewModels';
const sequence=[['tissue','slide'],['forceps','onion'],['water','slide'],['forceps','slide'],['lugol','slide'],['coverslip','slide'],['tissue','slide'],['slide','microscope']];
function prepared(mode:'latihan'|'ujian'='latihan'){let s=initial(mode);for(const t of epidermisTools)s=reducer(s,{type:'add',id:t.id});for(const [source,target] of sequence)s=reducer(s,{type:'interact',source,target});return s;}
function focused(s:State){return reducer(s,{type:'adjust',focus:68,offset:[0,0]});}
describe('epidermis preparation and microscopy',()=>{
 it('reuses PPE identities and the microscope registry',()=>{for(const id of ['goggles','coat','gloves'])expect(epidermisTools.find(t=>t.id===id)).toBe(tools.find(t=>t.id===id));expect(getPreviewAsset('microscope')?.path).toBe('/models/microscope.glb');});
 it('requires APD and ordered preparation with visual/audio events',()=>{const unsafe=reducer(initial('ujian'),{type:'add',id:'slide'});expect(unsafe.objects).toHaveLength(0);expect(unsafe.penalties.APD).toBe(5);let s=initial('latihan');for(const t of epidermisTools)s=reducer(s,{type:'add',id:t.id});expect(reducer(s,{type:'interact',source:'lugol',target:'slide'}).step).toBe(1);for(const [source,target] of sequence){const old=s;s=reducer(s,{type:'interact',source,target});expect(s.step).toBe(old.step+1);expect(s.motion?.source).toBe(source);expect(s.sound).not.toBe('error');}expect(s.step).toBe(9);expect(s.objects.find(o=>o.id==='slide')!.pos[1]).toBeGreaterThan(1);});
 it('requires both centering and focus, rejects invalid values, locks completed optics',()=>{let s=prepared();expect(ready(s)).toBe(false);expect(reducer(s,{type:'observe'}).step).toBe(9);s=reducer(s,{type:'adjust',focus:68});expect(ready(s)).toBe(false);s=focused(s);expect(ready(s)).toBe(true);expect(reducer(s,{type:'adjust',focus:NaN,offset:[Infinity,0]}).focus).toBe(68);s=reducer(s,{type:'observe'});expect(s.step).toBe(10);expect(reducer(s,{type:'adjust',focus:0})).toBe(s);});
 it('grades actual rendered regions, permits retries, and requires all three markings',()=>{let s=reducer(focused(prepared('ujian')),{type:'observe'});expect(reducer(s,{type:'submit'}).finished).toBe(false);s=reducer(s,{type:'mark',x:190,y:245});expect(s.marked).toHaveLength(0);expect(score(s)).toBe(95);for(const [x,y] of [[112,240],[190,245],[133,243]])s=reducer(s,{type:'mark',x,y});expect(s.marked).toEqual([0,1,2]);expect(s.attempts).toEqual([2,1,1]);expect(reducer(s,{type:'submit'}).finished).toBe(true);expect(structureAt(133,243)).toBe(2);});
 it('supports full marks, elapsed time, reset and practice step replay',()=>{let s=reducer(focused(prepared()),{type:'observe'});for(const [x,y] of [[112,240],[190,245],[133,243]])s=reducer(s,{type:'mark',x,y});s=reducer(s,{type:'submit'});expect(score(s)).toBe(100);expect(reducer(s,{type:'reset'})).toEqual(initial('latihan'));const expired=reducer(prepared('ujian'),{type:'tick',seconds:620});expect(expired.finished&&expired.expired).toBe(true);expect(expired.remaining).toBe(0);expect(score(expired)).toBeLessThan(100);const snapshot=prepared();expect(reducer(focused(snapshot),{type:'resetStep',snapshot}).focus).toBe(12);expect(reducer(prepared('ujian'),{type:'resetStep',snapshot}).mode).toBe('ujian');expect(reducer(snapshot,{type:'tick',seconds:600}).remaining).toBe(600);});
});
