// Course content is deliberately independent of the titration inventory.
export const equipment = [
 {id:'goggles',name:'Kacamata keselamatan',purpose:'Melindungi mata dari percikan bahan kimia.',features:'Lensa lebar, pelindung sisi tertutup, dan tali elastis; berbeda dari kacamata biasa.',use:'Atur tali hingga rapat dan nyaman sebelum membuka bahan.',safety:'Gunakan tipe chemical splash goggles; jangan melepasnya ketika bahan masih ditangani.'},
 {id:'coat',name:'Jas laboratorium',purpose:'Membantu melindungi kulit dan pakaian dari percikan ringan.',features:'Lengan panjang, bukaan depan berkancing, kerah, dan saku.',use:'Kancingkan jas dan pilih ukuran yang tidak mengganggu gerakan.',safety:'Jas bukan pelindung untuk semua bahan. Lepaskan jas yang terkontaminasi sesuai arahan guru.'},
 {id:'gloves',name:'Sarung tangan',purpose:'Mengurangi kontak tangan dengan bahan yang ditangani.',features:'Lapisan lentur menutup telapak dan jari; bahan sarung tangan menentukan ketahanannya.',use:'Pilih bahan yang sesuai SDS, periksa kerusakan, lalu kenakan pada tangan kering.',safety:'Tidak ada sarung tangan yang cocok untuk semua bahan. Ganti jika rusak dan jangan menyentuh wajah.'},
 {id:'stand',name:'Statif dan klem',purpose:'Menopang alat agar stabil selama percobaan.',features:'Alas berat, batang vertikal, penghubung, dan rahang penjepit.',use:'Atur tinggi klem dan jepit alat dengan tekanan secukupnya.',safety:'Tempatkan beban di atas alas; klem terlalu kuat dapat memecahkan kaca.'},
 {id:'burette',name:'Buret',purpose:'Mengalirkan cairan dengan volume terukur dan laju yang bisa diatur.',features:'Tabung panjang berskala, kran di bawah, dan ujung tetes.',use:'Pasang tegak, hilangkan gelembung pada ujung, lalu baca selisih skala awal dan akhir.',safety:'Isi pada ketinggian aman dan lepaskan corong sebelum membaca volume.'},
 {id:'flask',name:'Erlenmeyer',purpose:'Menampung dan mencampurkan larutan dengan gerakan memutar.',features:'Badan kerucut, dasar datar, dan leher sempit.',use:'Pegang leher lalu putar perlahan agar isi tercampur tanpa memercik.',safety:'Skalanya hanya perkiraan. Jangan memanaskan wadah tertutup rapat.'},
 {id:'beaker',name:'Gelas beker',purpose:'Menampung, melarutkan, dan mencampurkan bahan.',features:'Badan silinder lebar, dasar datar, dan cerat tuang.',use:'Aduk dengan batang pengaduk dan tuang melalui cerat.',safety:'Bukan alat ukur teliti. Periksa retak dan gunakan perlengkapan sesuai saat memegang kaca panas.'},
 {id:'cylinder',name:'Gelas ukur',purpose:'Mengukur volume cairan dengan ketelitian lebih baik daripada beker.',features:'Silinder tinggi berskala dengan kaki lebar dan cerat.',use:'Letakkan tegak di meja datar; baca meniskus sejajar mata.',safety:'Jangan digunakan untuk pemanasan atau mencampur dengan mengguncang kuat.'},
 {id:'volumetric',name:'Labu ukur',purpose:'Menyiapkan larutan dengan satu volume akhir yang ditentukan.',features:'Badan membulat, leher panjang, satu tanda batas, dan sumbat.',use:'Tambahkan pelarut sampai tanda batas, tutup, lalu balik perlahan untuk mencampur.',safety:'Jangan dipanaskan. Sesuaikan pembacaan dengan suhu kalibrasi yang tertera pada alat.'},
 {id:'pipette',name:'Pipet volumetrik',purpose:'Memindahkan satu volume cairan secara teliti.',features:'Pipa ramping dengan gondok di tengah dan satu tanda batas.',use:'Gunakan propipet, atur meniskus ke tanda, lalu alirkan sesuai petunjuk kalibrasi.',safety:'Jangan mengisap dengan mulut; jangan meniup sisa cairan kecuali alat memang bertipe blow-out.'},
 {id:'dropper',name:'Pipet tetes',purpose:'Memindahkan sedikit cairan secara bertetes.',features:'Tabung kecil berujung sempit dengan kepala karet.',use:'Tekan kepala sebelum mencelupkan ujung, lepaskan untuk mengambil cairan.',safety:'Bukan alat ukur volume teliti. Hindari menyentuhkan ujung ke bahan lain.'},
 {id:'propipette',name:'Propipet',purpose:'Membantu mengambil dan mengeluarkan cairan melalui pipet.',features:'Bola karet dengan katup pengatur udara, pengisapan, dan pengeluaran.',use:'Pasang perlahan pada pipet dan gunakan katup sesuai petunjuk alat.',safety:'Jangan memaksa kaca masuk atau membiarkan cairan tersedot ke bola karet.'},
 {id:'tube',name:'Tabung reaksi',purpose:'Menampung reaksi skala kecil atau pemanasan yang sesuai prosedur.',features:'Tabung terbuka tanpa kran, dengan dasar membulat.',use:'Letakkan dalam rak; gunakan penjepit bila perlu dipanaskan.',safety:'Arahkan mulut menjauhi orang dan jangan memanaskan tabung yang disumbat.'},
 {id:'rack',name:'Rak tabung reaksi',purpose:'Menjaga beberapa tabung reaksi tetap tegak.',features:'Deretan lubang pada penopang atas dan alas di bawahnya.',use:'Pilih lubang yang pas dan masukkan tabung perlahan hingga tersangga.',safety:'Letakkan stabil, jauh dari tepi meja; jangan membawa rak berisi tabung tanpa arahan.'},
 {id:'holder',name:'Penjepit tabung reaksi',purpose:'Memegang tabung saat tangan perlu dijauhkan dari panas.',features:'Rahang penjepit dengan pegangan panjang; dapat berbahan kayu atau logam.',use:'Jepit pada bagian atas tabung, bukan tepat di mulutnya.',safety:'Pastikan cengkeraman kuat; jangan arahkan mulut tabung ke diri sendiri atau teman.'},
 {id:'funnel',name:'Corong',purpose:'Membantu pemindahan cairan; dengan kertas saring dapat membantu penyaringan.',features:'Mulut kerucut terbuka lebar dan batang sempit.',use:'Topang corong dengan stabil dan tuang perlahan tanpa memenuhi mulutnya.',safety:'Jangan menekan batang kaca ke wadah; beri jalan udara agar aliran tidak tersendat.'},
 {id:'rod',name:'Batang pengaduk',purpose:'Mengaduk larutan dan membantu mengarahkan aliran saat menuang.',features:'Batang kaca padat dengan ujung membulat, tanpa rongga.',use:'Aduk perlahan tanpa membenturkan batang ke dinding wadah.',safety:'Periksa ujung yang retak; jangan memakai batang sebagai pengungkit.'},
 {id:'spatula',name:'Spatula',purpose:'Mengambil atau memindahkan sedikit bahan padat.',features:'Pegangan ramping dengan ujung datar atau berbentuk sendok.',use:'Ambil bahan memakai spatula bersih dan kering.',safety:'Jangan mengembalikan kelebihan bahan ke botol asal atau memakai satu spatula untuk bahan berbeda.'},
 {id:'mortar',name:'Mortar dan alu',purpose:'Menghaluskan padatan dan mencampurkannya secara mekanis.',features:'Mangkuk tebal dengan permukaan dalam kasar dan penumbuk membulat.',use:'Gerus sedikit demi sedikit dengan tekanan dan putaran terkendali.',safety:'Hindari debu. Jangan menggerus campuran reaktif atau bahan tak dikenal.'},
 {id:'burner',name:'Pembakar spiritus',purpose:'Memberikan sumber panas kecil dari bahan bakar alkohol.',features:'Reservoir, sumbu, dudukan sumbu, dan tutup pemadam.',use:'Gunakan hanya atas arahan guru; padamkan dengan tutup pemadam yang sesuai.',safety:'Jangan isi ulang saat menyala atau masih panas; jauhkan bahan mudah terbakar.'},
] as const;

export type EquipmentId = typeof equipment[number]['id'];
export const introQuestions = [
 {q:'Alat untuk menyiapkan larutan dengan satu volume akhir yang teliti adalah…',options:['Gelas beker','Labu ukur','Erlenmeyer'],answer:1,explanation:'Labu ukur memiliki satu tanda batas untuk volume akhir tertentu; skala beker dan Erlenmeyer hanya perkiraan.'},
 {q:'Alat apa yang membantu mengisap cairan ke dalam pipet dengan aman?',options:['Propipet','Batang pengaduk','Corong'],answer:0,explanation:'Propipet mengatur pengisapan dan pengeluaran cairan tanpa menggunakan mulut.'},
 {q:'Pictogram api di atas lingkaran menandakan…',options:['Gas bertekanan','Mudah terbakar saja','Pengoksidasi'],answer:2,explanation:'Pengoksidasi dapat menyebabkan atau memperhebat kebakaran, walaupun bahannya sendiri tidak harus mudah terbakar.'},
 {q:'Apa perbedaan tengkorak dan tanda seru?',options:['Keduanya selalu berarti bahaya yang sama','Tengkorak menandai toksisitas akut berat; tanda seru dapat berarti iritan atau berbahaya','Tanda seru berarti bahan aman'],answer:1,explanation:'Tengkorak digunakan untuk toksisitas akut yang dapat fatal atau toksik. Tanda seru antara lain untuk iritasi atau toksisitas akut kategori berbahaya yang lebih rendah.'},
 {q:'Sebelum memakai bahan dari suatu botol, kamu sebaiknya…',options:['Menilai keamanan dari warna cairan','Mencium langsung untuk mengenalinya','Membaca label dan SDS, lalu mengikuti arahan guru serta APD yang sesuai'],answer:2,explanation:'Identitas, konsentrasi, bahaya, APD, dan penanganan diperiksa dari label serta SDS produk, bukan warna atau bau.'},
] as const;

export function gradeIntroduction(answers: readonly number[]) {
 if (answers.length !== introQuestions.length || answers.some((answer,index)=>!Number.isInteger(answer)||answer<0||answer>=introQuestions[index].options.length)) return null;
 const incorrect=introQuestions.flatMap((question,index)=>answers[index]===question.answer?[]:[index]);
 return {score:introQuestions.length-incorrect.length,passed:incorrect.length<=1,incorrect};
}

export const completionKey='nalaraya:lab-intro-complete';
export function readCompletion(storage:Pick<Storage,'getItem'>) {try{return storage.getItem(completionKey)==='true'}catch{return false}}
export function saveCompletion(storage:Pick<Storage,'setItem'>) {try{storage.setItem(completionKey,'true');return true}catch{return false}}
